#!/usr/bin/env bash
# opencode-shared/init.sh
# Bootstraps an ESP-IDF project with full OpenCode support:
#   - LSP via esp-clangd (with cross-compiler query-driver)
#   - Agent skill symlinks (esp32-idf, esp32-patterns)
#   - IDF-aware shell wrapper for bash tool calls
#   - opencode.json with agent permissions and custom commands
#
# Usage:  ./opencode-shared/init.sh
# Re-run: safe to re-run; merges into existing opencode.json

set -euo pipefail
SHARED="$(cd "$(dirname "$0")" && pwd)"
PROJECT="$(pwd)"

# ── Colour helpers ────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
ok()   { echo -e "${GREEN}✅  $*${NC}"; }
warn() { echo -e "${YELLOW}⚠️   $*${NC}"; }
err()  { echo -e "${RED}❌  $*${NC}"; }

echo ""
echo "opencode-shared / ESP32 init"
echo "════════════════════════════════════════════════"

# ── 1. Detect IDF_PATH ────────────────────────────────────────────────────────
if [ -z "${IDF_PATH:-}" ]; then
    # Try common locations before giving up
    for candidate in "$HOME/esp/esp-idf" "$HOME/.espressif/esp-idf" "/opt/esp/idf"; do
        if [ -f "$candidate/export.sh" ]; then
            export IDF_PATH="$candidate"
            break
        fi
    done
fi

if [ -z "${IDF_PATH:-}" ] || [ ! -f "$IDF_PATH/export.sh" ]; then
    err "IDF_PATH not set or invalid.  Run:  . \$IDF_PATH/export.sh  first."
    exit 1
fi
ok "IDF_PATH: $IDF_PATH"

# Source IDF quietly to populate PATH with tool locations
. "$IDF_PATH/export.sh" > /dev/null 2>&1
ok "ESP-IDF environment sourced"

# ── 2. Resolve esp-clangd binary ─────────────────────────────────────────────
ESP_CLANGD=$(ls ~/.espressif/tools/esp-clang/*/esp-clang/bin/clangd 2>/dev/null | tail -1)
if [ -z "$ESP_CLANGD" ]; then
    warn "esp-clangd not found.  Run:  idf_tools.py install all"
    warn "Falling back to system clangd (NOT recommended for ESP32)"
    ESP_CLANGD=$(command -v clangd || echo "clangd")
fi
ok "esp-clangd: $ESP_CLANGD"

# ── 3. Detect IDF_TARGET and resolve cross-compiler ──────────────────────────
# Read from sdkconfig if present; otherwise default to esp32
if [ -f "$PROJECT/sdkconfig" ]; then
    IDF_TARGET=$(grep '^CONFIG_IDF_TARGET=' "$PROJECT/sdkconfig" \
                  | sed 's/CONFIG_IDF_TARGET="\(.*\)"/\1/' | head -1)
fi
IDF_TARGET="${IDF_TARGET:-esp32}"
ok "IDF_TARGET: $IDF_TARGET"

# Map target to toolchain prefix
case "$IDF_TARGET" in
    esp32|esp32s2|esp32s3)   TOOLCHAIN_PREFIX="xtensa-esp-elf" ;;
    esp32c3|esp32c6|esp32h2) TOOLCHAIN_PREFIX="riscv32-esp-elf" ;;
    *) warn "Unknown target $IDF_TARGET, defaulting to xtensa-esp-elf toolchain"
       TOOLCHAIN_PREFIX="xtensa-esp-elf" ;;
esac

CROSS_GCC=$(ls ~/.espressif/tools/${TOOLCHAIN_PREFIX}/*/bin/${TOOLCHAIN_PREFIX}-gcc 2>/dev/null | tail -1)
if [ -z "$CROSS_GCC" ]; then
    warn "Cross-compiler not found for $TOOLCHAIN_PREFIX"
    warn "Run: idf_tools.py install all"
    QUERY_DRIVER_GLOB="**/${TOOLCHAIN_PREFIX}-gcc"
else
    CROSS_GCC_DIR=$(dirname "$CROSS_GCC")
    # Glob covers all variants (xtensa-esp32-elf-gcc, xtensa-esp32s3-elf-gcc, etc.)
    QUERY_DRIVER_GLOB="${CROSS_GCC_DIR}/${TOOLCHAIN_PREFIX}-*-gcc"
    ok "Cross-compiler dir: $CROSS_GCC_DIR"
fi

# ── 4. Generate .opencode/esp-shell.sh ───────────────────────────────────────
mkdir -p "$PROJECT/.opencode"
SHELL_WRAPPER="$PROJECT/.opencode/esp-shell.sh"
cat > "$SHELL_WRAPPER" <<SHELLWRAP
#!/usr/bin/env bash
# .opencode/esp-shell.sh — auto-generated by opencode-shared/init.sh
# OpenCode uses this as the shell for ALL bash tool calls.
# Every agent command automatically has the ESP-IDF environment available.
IDF_PATH="\${IDF_PATH:-${IDF_PATH}}"
if [ -f "\$IDF_PATH/export.sh" ]; then
    . "\$IDF_PATH/export.sh" > /dev/null 2>&1
fi
exec /bin/bash "\$@"
SHELLWRAP
chmod +x "$SHELL_WRAPPER"
ok "Created .opencode/esp-shell.sh"

# ── 5. Generate .clangd ───────────────────────────────────────────────────────
CLANGD_FILE="$PROJECT/.clangd"
if [ -f "$CLANGD_FILE" ]; then
    warn ".clangd already exists — skipping (delete to regenerate)"
else
    # Flags to remove differ slightly by architecture
    if [[ "$TOOLCHAIN_PREFIX" == "xtensa-esp-elf" ]]; then
        EXTRA_REMOVE="    - -mlongcalls\n    - -mtext-section-literals\n    - -mfix-esp32-psram-cache-issue"
    else
        EXTRA_REMOVE="    - -march=rv32imc\n    - -mabi=ilp32\n    - -mno-relax"
    fi

    cat > "$CLANGD_FILE" <<CLANGDEOF
# .clangd — auto-generated by opencode-shared/init.sh
# Filters GCC-specific flags that esp-clangd rejects, points to compile_commands.json
CompileFlags:
  CompilationDatabase: build      # must run:  idf.py reconfigure

  Remove:
    # Architecture-specific flags clangd cannot parse
$(echo -e "$EXTRA_REMOVE")
    # GCC-specific optimisation flags
    - -fno-tree-switch-conversion
    - -fstrict-volatile-bitfields
    - -fno-jump-tables
    - --param=min-pagesize=0
    - -Wno-frame-address

Diagnostics:
  UnusedIncludes: Strict

Index:
  Background: Build                # index in background, don't stall the agent
CLANGDEOF
    ok "Created .clangd for $IDF_TARGET ($TOOLCHAIN_PREFIX)"
fi

# ── 6. Symlink skills into .opencode/skills/ ──────────────────────────────────
mkdir -p "$PROJECT/.opencode/skills"
for skill in esp32-idf esp32-patterns; do
    SRC="$SHARED/skills/$skill"
    DST="$PROJECT/.opencode/skills/$skill"
    if [ -d "$SRC" ]; then
        if [ -L "$DST" ] || [ -e "$DST" ]; then
            ok "Skill '$skill' already linked"
        else
            ln -sf "$SRC" "$DST"
            ok "Linked skill: $skill"
        fi
    else
        warn "Skill '$skill' not found in $SHARED/skills/ — skipping"
    fi
done

# ── 7. Generate / merge opencode.json using Python ────────────────────────────
# Python is always available in the ESP-IDF environment
python3 - "$ESP_CLANGD" "$QUERY_DRIVER_GLOB" "$IDF_PATH" <<PYEOF
import json, sys, os

esp_clangd    = sys.argv[1]
query_driver  = sys.argv[2]
idf_path      = sys.argv[3]
config_path   = 'opencode.json'

def deep_merge(base, override):
    """Recursively merge override into base; override wins on scalar conflicts."""
    result = dict(base)
    for k, v in override.items():
        if k in result and isinstance(result[k], dict) and isinstance(v, dict):
            result[k] = deep_merge(result[k], v)
        else:
            result[k] = v
    return result

# Read existing config (preserve user settings like model, provider, etc.)
existing = {}
if os.path.exists(config_path):
    try:
        with open(config_path) as f:
            existing = json.load(f)
        print(f"  [merge] Merging into existing {config_path}")
    except json.JSONDecodeError:
        print(f"  [warn]  Could not parse {config_path} — overwriting")

# ESP32 config layer
esp32 = {
    "\$schema": "https://opencode.ai/config.json",

    # IDF-aware shell: every agent bash call has IDF env pre-sourced
    "shell": ".opencode/esp-shell.sh",

    # LSP — override built-in clangd with esp-clangd
    "lsp": {
        "clangd": {
            "command": [
                esp_clangd,
                "--background-index",
                "--clang-tidy",
                "--completion-style=detailed",
                "--header-insertion=never",
                f"--query-driver={query_driver}",
                "--compile-commands-dir=build"
            ],
            # Pass IDF_PATH explicitly to the LSP server process
            "env": { "IDF_PATH": idf_path },
            "extensions": [".c", ".cpp", ".cc", ".cxx", ".h", ".hpp", ".hh"]
        }
    },

    # Watcher — ignore generated directories
    "watcher": {
        "ignore": [
            "build/**",
            "managed_components/**",
            "sdkconfig.old",
            "dependencies.lock"
        ]
    },

    # Global permissions (apply to all agents unless overridden per-agent)
    "permission": {
        "skill": { "*": "allow" },
        "lsp":   "allow",
        "bash": {
            "*":               "allow",
            "idf.py flash*":   "ask",     # require approval before touching hardware
            "idf.py erase*":   "ask",
            "idf.py fullclean":"ask"       # destructive: deletes entire build dir
        }
    },

    # Per-agent overrides — reference the user's 5 custom agent names
    "agent": {
        "dev": {
            "permission": {
                "skill": { "*": "allow" },
                "lsp":    "allow",
                "edit":   "allow",
                "bash": {
                    "*":               "allow",
                    "idf.py flash*":   "ask",
                    "idf.py erase*":   "ask",
                    "idf.py fullclean":"ask"
                }
            }
        },
        "qa": {
            "permission": {
                "skill": { "*": "allow" },
                "lsp":    "allow",
                "edit":   "deny",          # QA reads and runs, does not modify
                "bash": {
                    "*":             "allow",
                    "idf.py flash*": "ask",
                    "idf.py erase*": "ask"
                }
            }
        },
        "scout": {
            "permission": {
                "skill": { "*": "allow" },
                "lsp":    "allow",
                "edit":   "deny",          # scout is read-only
                "bash":   "deny"
            }
        },
        "plan": {
            "permission": {
                "skill": { "*": "allow" },
                "lsp":    "allow",
                "edit":   "deny",          # plan only reads and thinks
                "bash":   "deny"
            }
        },
        "mem": {
            "permission": {
                "skill": { "*": "allow" },
                "lsp":    "allow",
                "edit":   "allow",
                "bash":   { "*": "allow" }
            }
        }
    },

    # Custom slash-commands for ESP32 workflow
    "command": {
        "esp-build": {
            "description": "Build firmware — reports errors with file:line context",
            "template": (
                "Load the esp32-idf skill.\n"
                "Run: idf.py build 2>&1 | tee build.log\n"
                "Parse build.log: show each error with file/line/message, "
                "group warnings by severity, report binary size from the last output lines."
            ),
            "agent": "dev"
        },
        "esp-check": {
            "description": "Refresh LSP index (reconfigure) then report real errors",
            "template": (
                "Load the esp32-idf skill.\n"
                "Run: idf.py reconfigure  (refreshes compile_commands.json)\n"
                "Then check LSP diagnostics across all .c and .h files. "
                "Ignore errors inside build/ and esp-idf/components/. "
                "Report only errors in project source files."
            ),
            "agent": "dev"
        },
        "esp-flash": {
            "description": "Flash + monitor — usage: /esp-flash /dev/cu.usbserial-XXXX",
            "template": (
                "Load the esp32-idf skill.\n"
                "Flash and monitor: idf.py -p $ARGUMENTS flash monitor\n"
                "Decode any crash backtraces from monitor output."
            ),
            "agent": "dev"
        },
        "esp-size": {
            "description": "Show firmware binary size breakdown by component",
            "template": (
                "Load the esp32-idf skill.\n"
                "Run: idf.py size-components\n"
                "Show top 10 largest components, flag anything unexpectedly large."
            ),
            "agent": "qa"
        },
        "esp-debug": {
            "description": "Start OpenOCD/GDB debug session — usage: /esp-debug [board.cfg]",
            "template": (
                "Load the esp32-idf skill.\n"
                "Start OpenOCD: openocd -f $ARGUMENTS (default: board/esp32-wrover-kit.cfg)\n"
                "Provide the GDB connect command and useful initial breakpoints."
            ),
            "agent": "dev"
        },
        "esp-new-component": {
            "description": "Scaffold a new ESP-IDF component — usage: /esp-new-component my_name",
            "template": (
                "Load the esp32-patterns skill.\n"
                "Create a new ESP-IDF component named $ARGUMENTS with:\n"
                "  - components/$ARGUMENTS/CMakeLists.txt (using idf_component_register)\n"
                "  - components/$ARGUMENTS/include/$ARGUMENTS.h (public API)\n"
                "  - components/$ARGUMENTS/$ARGUMENTS.c (implementation skeleton)\n"
                "Follow the component structure pattern from the skill."
            ),
            "agent": "dev"
        }
    }
}

merged = deep_merge(existing, esp32)

with open(config_path, 'w') as f:
    json.dump(merged, f, indent=2)
    f.write('\n')

print(f"  [ok]    {config_path} written")
PYEOF

ok "opencode.json generated"

# ── 8. Ensure compile_commands.json exists ────────────────────────────────────
if [ ! -f "$PROJECT/build/compile_commands.json" ]; then
    warn "compile_commands.json missing — running idf.py reconfigure..."
    if idf.py reconfigure > /dev/null 2>&1; then
        ok "compile_commands.json created"
    else
        warn "idf.py reconfigure failed — run it manually and then restart OpenCode"
    fi
else
    AGE=$(( ($(date +%s) - $(stat -f %m "$PROJECT/build/compile_commands.json" 2>/dev/null || echo 0)) / 60 ))
    if [ "$AGE" -gt 120 ]; then
        warn "compile_commands.json is ${AGE}m old — consider: idf.py reconfigure"
    else
        ok "compile_commands.json OK (${AGE}m old)"
    fi
fi

# ── 9. Summary ────────────────────────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════════"
echo "Setup complete.  Start with:"
echo ""
echo "  opencode"
echo ""
echo "Useful slash commands:"
echo "  /esp-build           → build + error report"
echo "  /esp-check           → refresh LSP index + diagnostics"
echo "  /esp-flash <port>    → flash + monitor"
echo "  /esp-size            → binary size breakdown"
echo "  /esp-new-component   → scaffold new component"
echo ""
echo "Skills available to all agents:"
echo "  esp32-idf      → toolchain ops, LSP triage, build/flash/debug"
echo "  esp32-patterns → FreeRTOS, GPIO, SPI/I2C, NVS, C++ idioms"
echo "════════════════════════════════════════════════"
